myApp/config/routes.rb
Rails.application.routes.draw do
  apipie
  resources :groups
  get 'sessions/new'

  resources :projects
  get '/get_all_projects', to: 'projects#get_all_projects'

  resources :users
  post '/user_is_exist', to: 'users#is_exist'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

myApp/app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups
end

myApp/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.page(params[:page]).per(5)
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @users = @group.users
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit

  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: '组已经成功创建.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: '组已经成功修改.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: '组已经成功删除.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:group_name)
    end
end

myApp/app/helpers/groups_helper.rb
module GroupsHelper
end

myApp/app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :组名： %>
    <%= form.text_field :group_name, id: :group_group_name ,class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-info" %>
  </div>
<% end %>

myApp/app/views/groups/edit.html.erb
<h2>编辑组</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= render 'form', group: @group %>


  <%= link_to '查看', @group %> |
  <%= link_to '返回', groups_path %>
  </div>
</div>

myApp/app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h2><%= t :group_manage%></h2>

<table class="table table-bordered">
  <thead>
    <tr>
      <th style="display: none"></th>
      <th><%=t :group_name%></th>
      <th colspan="3"><%=t :operation%></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td style="display: none"><%= group.id %></td>
        <td><%= group.group_name %></td>
        <td><%= link_to "#{t('show')}", group %></td>
        <td><%= link_to "#{t('edit')}", edit_group_path(group) %></td>
        <td><%= link_to "#{t('delete')}", group, method: :delete, data: { confirm: '确定要删除改组吗?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @groups %>

<br>

<div class = "new"><%= link_to "#{t('new_group')}", new_group_path  %></div>

<div class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
        <p>One fine body&hellip;</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>
  $(".table tr").click(function(){
      $(".modal").modal();
      $(".modal-title").text($(this).find("td:eq(1)").text());
  });
</script>

myApp/app/views/groups/new.html.erb
<h2>新建组</h2>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= render 'form', group: @group %>

  <%= link_to '返回', groups_path %>
  </div>
</div>

myApp/app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>组名:</strong>
  <%= @group.group_name %>
</p>

<p>
  <strong>组成员:</strong>
  <% @users.each do |user| %>
      <%= link_to user.user_name, edit_user_path(user) %>
  <% end %>
</p>

<%= link_to '编辑', edit_group_path(@group) %> |
<%= link_to '返回', groups_path %>