myApp/config/routes.rb
Rails.application.routes.draw do
  apipie
  resources :groups
  get 'sessions/new'

  resources :projects
  get '/get_all_projects', to: 'projects#get_all_projects'

  resources :users
  post '/user_is_exist', to: 'users#is_exist'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

myApp/app/models/project.rb
class Project < ApplicationRecord
  validates_presence_of :project_name , {  message: "项目名不能为空" }
  has_many :user_projects , dependent: :destroy
  has_many :users, through: :user_projects
  # scope :is_delete, -> { where(is_delete: 0) }
   default_scope { where(is_delete: 0) }

end

myApp/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def_param_group :project do
    param :project_name, String
    param :project_type, String
    param :begin_at, Date
    param :end_at,Date
  end


  # GET /projects
  # GET /projects.json
  def index
    # @projects = Project.where( is_delete: 0).page(params[:page]).per(5)
    @projects = Project.page(params[:page]).per(5)

  end

  api :GET, '/projects/:id', '项目详情'
  param :id, :number
  example '[test]'
  # GET /projects/1
  # GET /projects/1.json
  def show
    @users = @project.users
  end

  api :POST, "/projects","新建项目"
  param_group :project
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  #   set_project函数中已经做了操作
  end

  def get_all_projects
    projects = Project.all
    render json:{data:projects}
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        # format.html { redirect_to @project, notice: '项目已经成功创建.' }
        format.html { redirect_to @project, notice: t(:notice) }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_path(@project), notice: '项目已经成功修改.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.is_delete = 1;
    @project.save
    @project.user_projects.destroy_all
    respond_to do |format|
      format.html { redirect_to projects_url, notice: '项目已经成功删除.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:project_name, :project_type, :begin_at, :end_at, :is_delete)
    end
end

myApp/app/helpers/projects_helper.rb
module ProjectsHelper
end

myApp/app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :项目名称 %>
    <%= form.text_field :project_name, id: :project_project_name ,class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :项目类型 %>
    <%= form.text_field :project_type, id: :project_project_type ,class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :开始时间 %>
    <%= form.date_field :begin_at, id: :project_begin_at ,value: project.begin_at,class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :结束时间 %>
    <%= form.date_field :end_at, id: :project_end_at ,value: project.end_at,class: 'form-control' %>
  </div>

    <!--<input type="hidden" name="project[is_delete]" id="project_is_delete" value="0"> -->
  <%= hidden_field(:project, :is_delete, :value => 0) %>

  <div class="actions">
    <%= form.submit class: "btn btn-info" %>
  </div>
<% end %>

myApp/app/views/projects/edit.html.erb
<h2>编辑项目</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= render 'form', project: @project %>

  <%= link_to '查看', @project %> |
  <%= link_to '返回', projects_path %>

  </div>
</div>

myApp/app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h2><%=t :project_manage%></h2>


<table class="table table-bordered">
  <thead>
    <tr>
      <th><%=t :project_name%></th>
      <th><%=t :project_type%></th>
      <th><%=t :project_begin_at%></th>
      <th><%=t :project_end_at%></th>

      <th colspan="3"><%=t :operation%></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.project_name %></td>
        <td><%= project.project_type %></td>
        <td><%= project.begin_at %></td>
        <td><%= project.end_at %></td>

        <td><%= link_to "#{t('show')}", project %></td>
        <td><%= link_to "#{t('edit')}", edit_project_path(project) %></td>
        <td><%= link_to "#{t('delete')}", project, method: :delete, data: { confirm: '你确定要删除该项目吗?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @projects %>

<br>

<div class="new"><%= link_to "#{t('new_project')}", new_project_path %></div>

myApp/app/views/projects/new.html.erb
<h2>新建项目</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= render 'form', project: @project %>

  <%= link_to '返回', projects_path %>

  </div>
</div>

myApp/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>


<div class="tabnav">
  <button class="btn" onclick="tranTab('project')">项目详情</button>
  <button class="btn" onclick="tranTab('user')">项目成员</button>
</div>

<div id="project" class="tab">
  <p>
    <strong>项目名称:</strong>
    <%= @project.project_name %>
  </p>

  <p>
    <strong>项目类型:</strong>
    <%= @project.project_type %>
  </p>

  <p>
    <strong>开始时间:</strong>
    <%= @project.begin_at %>
  </p>

  <p>
    <strong>结束时间:</strong>
    <%= @project.end_at %>
  </p>
</div>

<div id="user" class = "tab" style="display:none">
  <p>
    <strong>项目成员:</strong>
    <% @users.each do |user| %>
        <%= link_to user.user_name, edit_user_path(user) %>
    <% end %>
  </p>
</div>

<script>
    function tranTab(name) {

        $(".tab").css("display","none");
        $("#"+name).css("display","block");
    }
</script>












<%= link_to '编辑', edit_project_path(@project) %> |
<%= link_to '返回', projects_path %>